server:
  port: 8761
spring:
  zipkin:
    baseUrl: http://localhost:9411/zipkin/
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

